# Generated by Django 4.2.6 on 2023-10-22 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('report_date', models.DateField(default=datetime.date.today, verbose_name='date reported')),
                ('bug_type', models.CharField(choices=[('error', 'Error'), ('new_feature', 'New Feature'), ('enhancement', 'Enhancement'), ('security_vulnerability', 'Security Vulnerability'), ('others', 'Others')], default='error', max_length=25)),
                ('status', models.CharField(choices=[('to_do', 'To do'), ('in_progress', 'In progress'), ('done', 'Done'), ("Won't Fix", "Won't Fix"), ('Duplicate', 'Duplicate'), ('Invalid', 'Invalid')], default='to_do', max_length=15)),
            ],
        ),
    ]
